//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Control
    {
        public string ID { get; set; }
        public string 商品名 { get; set; }
        public Nullable<decimal> 単価 { get; set; }
        public Nullable<int> 総個数 { get; set; }
        public Nullable<decimal> 総額 { get; set; }
        public Nullable<System.DateTime> 登録日時 { get; set; }
    }
}
