//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class trdbEntities1 : DbContext
    {
        public trdbEntities1()
            : base("name=trdbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Goods_Receipt_Management> Goods_Receipt_Management { get; set; }
        public virtual DbSet<Inventory_Control> Inventory_Control { get; set; }
        public virtual DbSet<Product_Management> Product_Management { get; set; }
        public virtual DbSet<Sales_Management> Sales_Management { get; set; }
    }
}
