//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Management
    {
        public string ID { get; set; }
        public string 商品名 { get; set; }
        public Nullable<decimal> 単価 { get; set; }
        public Nullable<decimal> 販売価格 { get; set; }
        public string 産地 { get; set; }
    }
}
